# Generated by Django 4.2.2 on 2023-06-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgination', models.CharField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('vaccancies', models.IntegerField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('Type', models.CharField(blank=True)),
                ('workmode', models.CharField(blank=True)),
                ('experience_from', models.CharField(blank=True)),
                ('experience_to', models.CharField(blank=True)),
                ('job_description', models.TextField()),
                ('criteria', models.CharField(blank=True)),
                ('payscale_from', models.CharField(blank=True)),
                ('applicants', models.IntegerField(default=0)),
                ('hired_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.recruitersprofile')),
            ],
        ),
    ]
