# Generated by Django 4.2.2 on 2023-06-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='payscale_to',
            field=models.CharField(blank=True),
        ),
    ]
