# Generated by Django 4.2.2 on 2023-06-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_jobpost_payscale_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='vaccancies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
