# Generated by Django 4.2.2 on 2023-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_alter_jobpost_vaccancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitersprofile',
            name='post_balance',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
