# Generated by Django 4.2.2 on 2023-07-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitersprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
