# Generated by Django 4.2.2 on 2023-07-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_account_mobile'),
        ('employers', '0007_alter_recruitersprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'applied'), ('intervied', 'intervied'), ('shortlisted', 'shortlisted'), ('rejected', 'rejected')], default='applied', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.jobpost')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.recruitersprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
