# Generated by Django 4.2.2 on 2023-07-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('intervied', 'intervied'), ('shortlisted', 'shortlisted'), ('selected', 'selected'), ('rejected', 'rejected')], default='applied', max_length=15),
        ),
    ]
