# Generated by Django 4.2.2 on 2023-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_jobapplication_is_downloaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitersprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/'),
        ),
    ]
