# Generated by Django 4.2.2 on 2023-06-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
