# Generated by Django 4.2.2 on 2023-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.CharField(),
        ),
    ]
