# Generated by Django 4.2.2 on 2023-08-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_account_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
