# Generated by Django 4.2.2 on 2023-08-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_experience_end_alter_experience_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateField(),
        ),
    ]
