# Generated by Django 4.2.2 on 2023-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_experience_end_alter_experience_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
