# Generated by Django 4.2.2 on 2023-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_experience_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/certificates/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/profiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/resumes/'),
        ),
    ]
