# Generated by Django 4.2.2 on 2023-06-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planeName', models.CharField(max_length=100)),
                ('no_of_count', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
