# Generated by Django 4.2.2 on 2023-06-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postplans',
            old_name='planeName',
            new_name='planName',
        ),
    ]
