# Generated by Django 4.2.2 on 2023-06-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_rename_planename_postplans_planname'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplans',
            name='feature_four',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='postplans',
            name='feature_one',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='postplans',
            name='feature_three',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='postplans',
            name='feature_two',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
