# Generated by Django 4.2.2 on 2023-06-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_postplans_feature_four_postplans_feature_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postplans',
            name='feature_four',
        ),
    ]
